### ISSUE TITLE
Support qoi image format

### ISSUE THREAD

**Issue by sloganking** [not-fl3/macroquad#625]
Per https://github.com/image-rs/image/issues/1641, the `image` crate now supports the `qoi` file format. However attempting to run 
```rust
let texture = load_texture("image.qoi");
```
crashes with
```
thread 'main' panicked at 'The image format Qoi is not supported', /home/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.3.26/src/texture.rs:489:37
```

This happens on macroquad version "0.3.26", however it doesn't apear that macroquad v0.4.x supports qoi either.

**Comment by sloganking** [comment]
```rust
use macroquad::prelude::*;
use image::GenericImageView;

async fn load_texture_from_file(path: &str) -> Result<Texture2D, FileError> {
    // load image using image crate
    let image = image::open(path).map_err(|_| FileError {
        kind: miniquad::fs::Error::DownloadFailed,
        path: path.to_owned(),
    })?;

    // setup macroquad image
    let mut macro_image = Image::empty();
    macro_image.width = image.width().try_into().unwrap();
    macro_image.height = image.height().try_into().unwrap();
    macro_image.bytes = vec![0; (image.width() * image.height() * 4) as usize];

    // transfer image pixels to macroquad image
    for x in 0..image.width() {
        for y in 0..image.height() {
            let pix = image.get_pixel(x, y);
            macro_image.set_pixel(x, y, pix.0.into())
        }
    }

    Ok(Texture2D::from_image(&macro_image))
}
```

A work around for now could be to import the `image` crate and use this custom function `load_texture_from_file()` instead of macroquad's `load_texture()`. But this adds dependencies and makes image decoding less performant. And image decode speed is one of `qoi`'s primary benefit.

**Comment by not-fl3** [comment]
> Per [image-rs/image#1641](https://github.com/image-rs/image/issues/1641), the `image` crate now supports the `qoi` file format. However attempting to run
> 
> ```rust
> use macroquad::prelude::*;
> 
> let texture = load_texture("image.qoi");
> ```
> 
> crashes with
> 
> ```
> thread 'main' panicked at 'The image format Qoi is not supported', /home/username/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.3.26/src/texture.rs:489:37
> ```
> 
> This happens on macroquad `v0.3.26`, however it doesn't apear that macroquad `v0.4.x` supports qoi either.

Cargo features are additive, so adding an image crate with the same version as macroquad but with an extra feature to the project's Cargo.toml will add this feature to the image crate.
